### ISSUE TITLE
replacing loops with purrr::map

### ISSUE THREAD

**Issue by ratnanil** [froborg/PatTr-Coding#10]
https://github.com/froborg/PatTr-Coding/blob/1a76038242db7f6a66fc4ea09daae94559462a4d/Exercise3/Exercise3.R#L167-L177<br/><br/>This is how you could solve this with `purrr::map`:

```
comparison_df <- map_dfr(2:6, function(x){
  tibble(
    trajID = x,
    DTW = DTW(pedestrians_list[[1]], pedestrians_list[[x]]),
    EditDist = EditDist(pedestrians_list[[1]], pedestrians_list[[x]]),
    Frechet = Frechet(pedestrians_list[[1]], pedestrians_list[[x]]),
    LCSS = LCSS(pedestrians_list[[1]], pedestrians_list[[x]],5,4,4)
  )
})
```

see [our solutions](https://computationalmovementanalysis.github.io/W03_05_solutions.html) for more information

**Comment by froborg** [comment]
Oh, this is so much nicer!
Did not know enough about purrr's map functions to come up with this solution. Thanks!
