### ISSUE TITLE
st_drop_geometry

### ISSUE THREAD

**Issue by ratnanil** [froborg/PatTr-Coding#6]
https://github.com/froborg/PatTr-Coding/blob/b42125b82382091825c6216a91f7637b647fc60a/Exercise2/Exercise2.R#L32-L37<br/><br/>You might have noticed that this operation makes a multipoint object out of the wildboar locations. If you want to avoid this in the future (this operation might take a long time), simply use `st_drop_geometry` like so:

```
wildschwein_BE %>%                         # Take wildschwein...
  st_drop_geometry() %>%
  group_by(TierID) %>%                     # ...group it by TierID
  summarise(                               # Summarise the data...
    min_time = min(DatetimeUTC,na.rm = T), # ...by calculating the min & max timelag
    max_time = max(DatetimeUTC,na.rm=T)
  )
```

**Comment by froborg** [comment]
Thanks for the suggestion, this is really helpful!
