### ISSUE TITLE
Issue with timezones (I think)

### ISSUE THREAD

**Issue by froborg** [froborg/PatTr-Coding#8]
Hi @ratnanil , hi @KimboGilda 

I have an issue with Exercise 4, Task 2
https://github.com/froborg/PatTr-Coding/blob/main/Exercise4/Exercise4.Rmd#L42-47
```
ws_filter <- wildschwein %>%
  filter(TierName == "Sabi" | TierName == 'Rosa') %>%
  filter(DatetimeUTC >= "2015-04-01" & DatetimeUTC <= "2015-04-16")
```
The resulting file starts with the first entry already at 31.03. at 22:00 instead of 01.04. at 00:00. I suspect a timezone issue but have no idea how to fix this in a nice way. Can you please advice? Thanks!

**Comment by ratnanil** [comment]
sorry for the late answer! Coercing your string to a POSIXct takes your systems locale as the time zone. to fix this, try the following

```
ws_filter <- wildschwein %>%
  filter(TierName == "Sabi" | TierName == 'Rosa') %>%
  filter(DatetimeUTC >= as.POSIXct("2015-04-01", tz = "UTC") & DatetimeUTC <= as.POSIXct("2015-04-16")
```

**Comment by froborg** [comment]
works, thanks
