### ISSUE TITLE
split and map

### ISSUE THREAD

**Issue by ratnanil** [froborg/PatTr-Coding#9]
https://github.com/froborg/PatTr-Coding/blob/1a76038242db7f6a66fc4ea09daae94559462a4d/Exercise3/Exercise3.R#L161-L166<br/><br/>Nice use of `split`! Here is a suggestion how you could refactor your code a little bit:

```
traj_list <- pedestrians %>% 
  split(.$TrajID) %>%
  map(~as.matrix(dplyr::select(.x, E, N)))
```

or (which is the same thing, without the `~`)

```
traj_list <- pedestrians %>% 
  split(.$TrajID) %>%
  map(function(x){
      x %>%                     # <- nested pipe!
        dplyr::select(E, N) %>%
        as.matrix()
  })
```

**Comment by froborg** [comment]
Thanks for the suggestion!
I like the first approach better and included that in my code.
